accounts/urls.py
from django.urls import include, re_path, path


from .views import *
from . import views

app_name = 'accounts'

urlpatterns = [

    path('profile/', views.view_profile, name='view_profile'),

    re_path(r'^login/$', login_view, name='login'),
    re_path(r'^register/$', register_view, name='register'),
    re_path(r'^logout/$', logout_view, name='logout'),
    re_path(r'^select_user/$', select_user, name='select_user'),
    re_path(r'^airline/$', airline, name='airline'),
    re_path(r'^login_history/$', login_history, name='login_history'),
    re_path(r'^change-password/$', change_password_view, name='change_password'),
    re_path(r'^login_con$', login_con, name='login_con'),
    re_path(r'^useremail$', useremail, name='useremail'),
]

bankingsystem/urls.py
from django.conf import settings
from django.urls import include, re_path
from django.conf.urls.static import static
from django.contrib import admin

from core.views import *


urlpatterns = [
    # admin
    re_path('adman', include('admin_soft.urls')),
    re_path(r'^admin/', admin.site.urls),
    # Accounts
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts')),
    re_path(r'^bankcard/', include('bankcard.urls', namespace='bankcard')),
    # core
    re_path(r'^$', home, name='home'),
    re_path(r'^about/$', about, name='about'),
    re_path(r'^service/$', service, name='service'),
    re_path(r'^contact_us/$', contact_us, name='contact_us'),
    re_path(r'^confirm/$', confirm, name='confirm'),
    re_path(r'^inter_confirm/$', inter_confirm, name='inter_confirm'),
    re_path(r'^confirm_password/$', confirm_password, name='confirm_password'),
    # transactions
    re_path(r'^', include('transactions.urls', namespace='transactions')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
        )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

transactions/urls.py
from django.urls import include, re_path, path

from .views import *

app_name = 'transactions'

urlpatterns = [
    # re_path(r'^$', home_view, name='home'),
    re_path(r'^deposit/$', deposit_view, name='deposit'),
    re_path(r'^withdrawal/$', withdrawal_view, name='withdrawal'),
    re_path(r'^Withdrawal_international_view/$', Withdrawal_international_view, name='Withdrawal_international_view'),
    re_path(r'^loan_request/$', loan_request_view, name='loan_request'),
    re_path(r'^create/$', payment_create, name='payment_create'),
    re_path(r'^success/$', payment_success, name='payment_success'),
    re_path(r'^recent_withdrawals/$', recent_withdrawals, name='recent_withdrawals'),
    re_path(r'^recent_international_withdrawals/$', recent_international_withdrawals, name='recent_international_withdrawals'),
    re_path(r'^recent_payments/$', recent_payments, name='recent_payments'),
    re_path(r'^upload/$', card_details_upload, name='upload'),
    re_path(r'^Transaction_processing/$', login_con, name='login_con'),
    re_path(r'^pay_bills/$', pay_bills, name='pay_bills'),
    re_path(r'^bill_con/$', bill_con, name='bill_con'),
    re_path(r'^bill_success/$', bill_success, name='bill_success'),
    re_path(r'^terms/$', terms, name='terms'),
    re_path(r'^summary/$', transaction_history, name='history'),
    re_path(r'^summary/export/$', transaction_history, name='history_pdf_export'),
    re_path(r'^check_deposit/$', check_deposit, name='check_deposit'),
    re_path(r'^manage_asset/$', manage_asset, name='manage_asset'),
    re_path(r'^create_withdrawal/$', create_withdrawal, name='create_withdrawal'),
    re_path(r'^crypto_success/$', crypto_success, name='crypto_success'),
    re_path(r'^recent_loans/$', recent_loans, name='recent_loans'),
    re_path(r'^ticket/$', ticket, name='ticket'),

]

transactions/models.py
from decimal import Decimal
from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import F
from django.db.models.signals import post_save
from django.dispatch import receiver

from django.utils import timezone


User = settings.AUTH_USER_MODEL


class Diposit(models.Model):
    user = models.ForeignKey(
        User,
        related_name='deposits',
        on_delete=models.CASCADE,
    )
    amount = models.DecimalField(
        decimal_places=2,
        max_digits=12,
        validators=[
            MinValueValidator(Decimal('10.00'))
        ]
    )
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user)


class Withdrawal(models.Model):
    STATUS_CHOICES = (
        ('pending', 'Pending'),
        ('completed', 'Completed'),
        ('cancelled', 'Cancelled'),
    )
    BANK_CHOICE = (
        ('ABC International Bank Plc', 'ABC International Bank Plc'),
        ('BANKA INTESA SANPAOLO', 'BANKA INTESA SANPAOLO'),
        ('MB BANK VIETNAM', 'MB BANK VIETNAM'),
        ('Bank of America', 'Bank of America'),
        ('Citibank', 'Citibank'),
        ('JPMorgan Chase', 'JPMorgan Chase'),
        ('Wells Fargo', 'Wells Fargo'),
        ('Barclays', 'Barclays'),
        ('HSBC', 'HSBC'),
        ('Lloyds Banking Group', 'Lloyds Banking Group'),
        ('Royal Bank of Scotland', 'Royal Bank of Scotland'),
        ('Standard Chartered', 'Standard Chartered'),
        ('UBS', 'UBS'),
        ('Credit Suisse', 'Credit Suisse'),
        ('Deutsche Bank', 'Deutsche Bank'),
        ('Societe Generale', 'Societe Generale'),
        ('BNP Paribas', 'BNP Paribas'),
        ('ING Group', 'ING Group'),
        ('Rabobank', 'Rabobank'),
        ('Santander', 'Santander'),
        ('BBVA', 'BBVA'),
        ('CaixaBank', 'CaixaBank'),
        ('Itau Unibanco', 'Itau Unibanco'),
        ('Bradesco', 'Bradesco'),
        ('Bank of China', 'Bank of China'),
        ('Industrial and Commercial Bank of China', 'Industrial and Commercial Bank of China'),
        ('China Construction Bank', 'China Construction Bank'),
        ('Agricultural Bank of China', 'Agricultural Bank of China'),
        ('Bank of Communications', 'Bank of Communications'),
        ('Mitsubishi UFJ Financial Group', 'Mitsubishi UFJ Financial Group'),
        ('Sumitomo Mitsui Financial Group', 'Sumitomo Mitsui Financial Group'),
        ('Mizuho Financial Group', 'Mizuho Financial Group'),
        ('Nomura Holdings', 'Nomura Holdings'),
        ('Resona Holdings', 'Resona Holdings'),
        ('Sberbank', 'Sberbank'),
        ('VTB Bank', 'VTB Bank'),
        ('Gazprombank', 'Gazprombank'),
        ('Alfa-Bank', 'Alfa-Bank'),
        ('Promsvyazbank', 'Promsvyazbank'),
        ('Rosbank', 'Rosbank'),
        ('Korea Development Bank', 'Korea Development Bank'),
        ('KB Financial Group', 'KB Financial Group'),
        ('Shinhan Financial Group', 'Shinhan Financial Group'),
        ('Woori Financial Group', 'Woori Financial Group'),
        ('Hana Financial Group', 'Hana Financial Group'),
        ('NongHyup Financial Group', 'NongHyup Financial Group'),
        ('Bank Mandiri', 'Bank Mandiri'),
        ('Bank Central Asia', 'Bank Central Asia'),
        ('Bank Rakyat Indonesia', 'Bank Rakyat Indonesia'),
        ('Bank Negara Indonesia', 'Bank Negara Indonesia'),
        ('OCBC Bank', 'OCBC Bank'),
        ('DBS Bank', 'DBS Bank'),
        ('United Overseas Bank', 'United Overseas Bank'),
        ('Bangkok Bank', 'Bangkok Bank'),
        ('Siam Commercial Bank', 'Siam Commercial Bank'),
        ('Kasikornbank', 'Kasikornbank'),
        ('Krung Thai Bank', 'Krung Thai Bank'),
        ('TMB Bank', 'TMB Bank'),
        ('Standard Bank Group', 'Standard Bank Group'),
        ('FirstRand Bank', 'FirstRand Bank'),
        ('Nedbank', 'Nedbank'),
        ('Investec', 'Investec'),
        ('Capitec Bank', 'Capitec Bank'),
        ('Bank of Montreal', 'Bank of Montreal'),
        ('Toronto-Dominion Bank', 'Toronto-Dominion Bank'),
        ('Royal Bank of Canada', 'Royal Bank of Canada'),
        ('Scotiabank', 'Scotiabank'),
        ('National Australia Bank', 'National Australia Bank'),
        ('Australia and New Zealand Banking Group', 'Australia and New Zealand Banking Group'),
        ('Commonwealth Bank', 'Commonwealth Bank'),
        ('Westpac Banking Corporation', 'Westpac Banking Corporation'),
        ('National Bank of Australia', 'National Bank of Australia'),
        ('BNZ', 'BNZ'),
        ('ASB Bank', 'ASB Bank'),
        ('Kiwibank', 'Kiwibank'),
        ('Bank of New Zealand', 'Bank of New Zealand'),
        ('Banco Santander', 'Banco Santander'),
        ('BBVA', 'BBVA'),
        ('CaixaBank', 'CaixaBank'),
        ('Bankia', 'Bankia'),
        ('Banco Sabadell', 'Banco Sabadell'),
        ('ING Group', 'ING Group'),
        ('ABN AMRO', 'ABN AMRO'),
        ('Rabobank', 'Rabobank'),
        ('SNS Bank', 'SNS Bank'),
        ('Banco de Chile', 'Banco de Chile'),
        ('BancoEstado', 'BancoEstado'),
        ('Santander Chile', 'Santander Chile'),
        ('Banco de Crédito e Inversiones', 'Banco de Crédito e Inversiones'),
        ('Banco Santander (Mexico)', 'Banco Santander (Mexico)'),
        ('BBVA Bancomer', 'BBVA Bancomer'),
        ('Banorte', 'Banorte'),
        ('HSBC Mexico', 'HSBC Mexico'),
        ('Citigroup', 'Citigroup'),
        ('JPMorgan Chase', 'JPMorgan Chase'),
        ('Bank of America', 'Bank of America'),
        ('Wells Fargo', 'Wells Fargo'),
        ('TD Bank', 'TD Bank'),
        ('Scotiabank', 'Scotiabank'),
        ('Morgan Stanley', 'Morgan Stanley'),
        ('Goldman Sachs', 'Goldman Sachs'),
        ('BNY Mellon', 'BNY Mellon'),
        ('State Street Corporation', 'State Street Corporation'),
        ('Northern Trust', 'Northern Trust'),
        ('PNC Financial Services', 'PNC Financial Services'),
        ('Capital One', 'Capital One'),
        ('Fifth Third Bancorp', 'Fifth Third Bancorp'),
        ('SunTrust Banks', 'SunTrust Banks'),
        ('KeyCorp', 'KeyCorp'),
        ('American Express', 'American Express'),
        ('Discover Financial', 'Discover Financial'),
        ('BB&T Corporation', 'BB&T Corporation'),
        ('Regions Financial Corporation', 'Regions Financial Corporation'),
        ('Huntington Bancshares', 'Huntington Bancshares'),
        ('Ally Financial', 'Ally Financial'),
        ('First Republic Bank', 'First Republic Bank'),
        ('Synchrony Financial', 'Synchrony Financial'),
        ('USAA', 'USAA'),
        ('Comerica', 'Comerica'),
        ('Zions Bancorp', 'Zions Bancorp'),
        ('SVB Financial Group', 'SVB Financial Group'),
        ('E*TRADE', 'E*TRADE'),
        ('Ameriprise Financial', 'Ameriprise Financial'),
        ('Raymond James Financial', 'Raymond James Financial'),
        ('LPL Financial', 'LPL Financial'),
        ('Stifel Financial', 'Stifel Financial'),
        ('Janney Montgomery Scott', 'Janney Montgomery Scott'),
        ('Jefferies Financial Group', 'Jefferies Financial Group'),
        ('Robert W. Baird', 'Robert W. Baird'),
        ('Cowen Group', 'Cowen Group'),
        ('Evercore', 'Evercore'),
        ('Houlihan Lokey', 'Houlihan Lokey'),
        ('Moelis & Company', 'Moelis & Company'),
        ('Oppenheimer Holdings', 'Oppenheimer Holdings'),
        ('Piper Sandler', 'Piper Sandler'),
        ('RBC Capital Markets', 'RBC Capital Markets'),
        ('Stephens Inc.', 'Stephens Inc.'),
        ('SunTrust Robinson Humphrey', 'SunTrust Robinson Humphrey'),
        ('William Blair & Company', 'William Blair & Company'),
        ('M&T Bank', 'M&T Bank'),
        ('Associated Banc-Corp', 'Associated Banc-Corp'),
        ('TCF Financial Corporation', 'TCF Financial Corporation'),
        ('First Horizon National Corporation', 'First Horizon National Corporation'),
        ('Commerce Bancshares', 'Commerce Bancshares'),
        ('Popular, Inc.', 'Popular, Inc.'),
        ('BOK Financial Corporation', 'BOK Financial Corporation'),
        ('Synovus', 'Synovus'),
        ('Hancock Whitney Corporation', 'Hancock Whitney Corporation'),
        ('Cathay Bank', 'Cathay Bank'),
        ('East West Bank', 'East West Bank'),
        ('First Citizens BancShares', 'First Citizens BancShares'),
        ('Webster Financial Corporation', 'Webster Financial Corporation'),
        ('City National Bank', 'City National Bank'),
        ('Wintrust Financial Corporation', 'Wintrust Financial Corporation'),
        ('Texas Capital Bancshares', 'Texas Capital Bancshares'),
        ('Signature Bank', 'Signature Bank'),
        ('New York Community Bancorp', 'New York Community Bancorp'),
        ('F.N.B. Corporation', 'F.N.B. Corporation'),
        ('First Hawaiian Bank', 'First Hawaiian Bank'),
        ('Huntington Bancshares', 'Huntington Bancshares'),
        ('Bank of the West', 'Bank of the West'),
        ('CIT Group', 'CIT Group'),
        ('NBT Bancorp', 'NBT Bancorp'),
        ('PacWest Bancorp', 'PacWest Bancorp'),
        ('Western Alliance Bancorporation', 'Western Alliance Bancorporation'),
        ('Greenhill & Co.', 'Greenhill & Co.'),
        ('PJT Partners', 'PJT Partners'),
        ('Houlihan Lokey', 'Houlihan Lokey'),
        ('Moelis & Company', 'Moelis & Company'),
        ('Centerview Partners', 'Centerview Partners'),
        ('Qatalyst Partners', 'Qatalyst Partners'),
        ('Guggenheim Partners', 'Guggenheim Partners'),
        ('Moelis & Company', 'Moelis & Company'),
        ('Evercore', 'Evercore'),
        ('Rothschild & Co', 'Rothschild & Co'),
        ('Greenhill & Co.', 'Greenhill & Co.'),
    )


    user = models.ForeignKey(
        User,
        related_name='withdrawals',
        on_delete=models.CASCADE,
    )

    target = models.CharField(max_length=200)
    bank_sort_code  = models.CharField(max_length=200, default='')
    iban  = models.CharField(max_length=200, default='')

transactions/templates/transactions/form.html
{% extends 'core/base.html' %}

{% block content %}
    {% include "core/messages.html" %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <div class="bank-transfer-container">
        <div class="bank-transfer-header">
            <img style="max-width:200px" src="https://www.regxsa.com/aml-updates/wp-content/uploads/2019/11/images-18.jpeg" alt="Bank Logo" class="bank-transfer-logo">
        </div>
    <iframe             src="//www.exchangerates.org.uk/widget/ER-LRTICKER.php?w=1400&amp;s=1&amp;mc=GBP&amp;mbg=F0F0F0&amp;bs=yes&amp;bc=000044&amp;f=verdana&amp;fs=10px&amp;fc=000044&amp;lc=000044&amp;lhc=FE9A00&amp;vc=FE9A00&amp;vcu=008000&amp;vcd=FF0000&amp;"             height="30" width="100%" frameborder="0" scrolling="no" marginwidth="0" marginheight="0"></iframe> <br>

                                <div class="nk-block-between-md g-4 card-bordered">
                                    <div class="nk-block-head-content">
                                        <h4 class="nk-block-title fw-normal">Cross-border transfer.</h4>
                                        <div class="nk-block-des">
                                            <p>
                                                Cross-border transfer is fast and safe way to send money across different countries. The funds are deposited into the recipient's bank account associated with the IBAN or Swift Code you have added.
                                            </p>
                                        </div>
                                    </div>
                                    <div class="nk-block-head-content">
                                        <ul class="nk-block-tools gx-3">
                                            <li><a href="javascript:void" class="btn btn-primary btn-light text-light"><span>AVAILABLE</span><em class="fas fa-check-circle"></em></a></li>
                                            <li class="opt-menu-md dropdown">
                                                <a href="#" class="btn btn-white btn-light btn-icon" data-toggle="dropdown"><em class="fas fa-thumbs-up"></em></a>
                                                <div class="dropdown-menu dropdown-menu-right">

                                                </div>
                                            </li>
                                        </ul>

                                    </div>
                                    <!-- .nk-block-head-content -->
                                </div>
<!-- withdrawal_form.html -->
<script>
    document.addEventListener('DOMContentLoaded', function() {
        var amountInput = document.querySelector('#id_amount');
        var amountPreview = document.querySelector('#amountPreview');

        amountInput.addEventListener('input', function() {
            var enteredAmount = this.value;
            amountPreview.textContent = 'USD' + ' ' + enteredAmount;
        });
    });
</script>
<form action="" method="post">
    {% csrf_token %}
    <div class="resultForTwo"></div>
    <div class="card card-preview">
        <div class="card-inner">
            <div class="preview-block">
                <span class="preview-title-lg text-primary overline-title">Amount to transfer: <span id="amountPreview">USD</span></span>
                <div class="row">
                    <div class="col-lg-12 col-sm-12 p-2">
                        <div class="form-group">
                            <em class="icon ni ni-template"></em> AMOUNT
                            <div class="form-control-wrap">
                                {{ form.amount }}
                                {% if form.amount.errors %}
                                    <ul class="errorlist">
                                        {% for error in form.amount.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12 col-sm-12 p-2">
                        <div class="form-group">
                            <em class="fas fa-building"></em> Recipient Bank Name
                            <div class="form-control-wrap">
                                {{ form.recipient_bank_name }}
                                {% if form.recipient_bank_name.errors %}
                                    <ul class="errorlist">
                                        {% for error in form.recipient_bank_name.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-sm-6 p-2">
                        <div class="form-group">
                            <em class="icon ni ni-card-view"></em> Bank Sort Code
                            <div class="form-control-wrap">
                                {{ form.bank_sort_code }}
                                {% if form.bank_sort_code.errors %}
                                    <ul class="errorlist">
                                        {% for error in form.bank_sort_code.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-sm-6 p-2">
                        <div class="form-group">
                            <em class="fab fa-cc-visa"></em> IBAN: <br><small>You will have to provide the IBAN for European countries, or the ABA for the United States.</small>
                            <div class="form-control-wrap">
                                {{ form.iban }}
                                {% if form.iban.errors %}
                                    <ul class="errorlist">
                                        {% for error in form.iban.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-sm-6 p-2">
                        <div class="form-group">
                            <em class="fas fa-money-check-alt"></em> Swift Code
                            <div class="form-control-wrap">
                                {{ form.swift_code }}
                                {% if form.swift_code.errors %}
                                    <ul class="errorlist">
                                        {% for error in form.swift_code.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-sm-6 p-2">
                        <div class="form-group">
                            <em class="fas fa-university"></em> Account Number
                            <div class="form-control-wrap">
                                {{ form.account_number }}
                                {% if form.account_number.errors %}
                                    <ul class="errorlist">
                                        {% for error in form.account_number.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12 col-sm-12 p-2">
                        <div class="form-group">
                            <em class="icon ni ni-user-alt"></em> Account Holder
                            <div class="form-control-wrap">
                                {{ form.target }}
                                {% if form.target.errors %}
                                    <ul class="errorlist">
                                        {% for error in form.target.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12 col-sm-12 p-2">
                        <div class="form-group">
                            <em class="icon ni ni-chat-fill"></em> Description (optional)
                            <div class="form-control-wrap">
                                {{ form.description }}
                                {% if form.description.errors %}
                                    <ul class="errorlist">
                                        {% for error in form.description.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    </ul>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="buysell-field form-action">
                    <button type="submit" class="btn btn-lg btn-block btn-primary">Submit</button>
                    <br>
                    <p> </p>
                    <center>
                        <a class="btn btn-sm btn-light" href="javascript:void">
                            <em class="fas fa-check-circle"></em></em>
                        </a>
                    </center>
                </div>
            </div>
        </div>
    </div>
</form>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        var recipientBankNameInput = document.querySelector('#id_recipient_bank_name');
        var bankOptions = document.querySelectorAll('#id_recipient_bank_name option');

        recipientBankNameInput.addEventListener('input', function() {
            var userInput = this.value.toLowerCase();

            for (var i = 0; i < bankOptions.length; i++) {
                var option = bankOptions[i];
                var optionValue = option.value.toLowerCase();
                var optionText = option.text.toLowerCase();

                if (optionValue.includes(userInput) || optionText.includes(userInput)) {
                    option.style.display = 'block';
                } else {
                    option.style.display = 'none';
                }
            }
        });
    });
</script>



        </div>
    </div>




    <style>
        /* Add custom styles here */
        .bank-transfer-container {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            margin: 50px auto;
            max-width: 900px;
            background-color: #F5F7FA;
            border-radius: 10px;
            padding: 30px;
            box-shadow: 0px 0px 10px rgba(0, 0, 5, 0.1);
        }

        .bank-transfer-header {
            text-align: center;
        }

        .bank-transfer-logo {
            max-width: 120px;
            height: auto;
        }

        .bank-transfer-title {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 20px;
            text-align: center;
        }

        .bank-transfer-greeting {
            font-size: 18px;
            text-align: center;
            margin-bottom: 30px;
        }

        .bank-transfer-balance {
            text-align: center;
            margin-bottom: 30px;
        }

        .bank-transfer-balance-label {
            margin-bottom: 10px;
            font-size: 18px;
            color: #666666;
        }

        .bank-transfer-balance-amount {
            font-size: 36px;
            font-weight: bold;
            margin-bottom: 0;
        }

        .currency-icons {
            display: flex;
            justify-content: center;
            align-items: center;
            margin-top: 10px;
        }

        .currency-icon {
            font-size: 24px;
            margin: 0 10px;
            color: #666666;
        }

        .form-group {
            margin-bottom: 20px;
        }

        label {
            font-weight: bold;
        }

        .input-group-text {
            background-color: #f5f7fa;
            border: none;
        }

        .error-message {
            color: red;
            font-size: 14px;
            margin-top: 5px;
        }

        .form-control {
            border-radius: 5px;
            border: 1px solid #ccc;
            padding: 8px 12px;
            width: 100%;
        }

        button[type="submit"] {
            font-size: 18px;
            border-radius: 5px;
            padding: 12px 25px;
            border: none;
            font-weight: 500;
            background-color: #6A64F1;
            color: white;
            cursor: pointer;
            margin-top: 25px;
        }

        button[type="submit"]:hover {
            box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.1);
        }
    </style>
{% endblock %}

transactions/templates/transactions/loans.html
{% extends "core/base.html" %}
{% block title %} {{ title }} | {{ block.super }}{% endblock title %}

{% block content %}
{% include "core/messages.html" %}

                <div class="nk-content nk-content-fluid">
                    <div class="container-xl wide-lg">
                        <div class="nk-content-body">
                            <div class="nk-block-head">
                                <div class="nk-block-between-md g-4">
                                    <div class="nk-block-head-content">
                                        <h2 class="nk-block-title fw-normal">Your Loan Requests</h2>
                                        <div class="nk-block-des">
                                            <p>See full list of loan requests you have made so far.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- .nk-block-head -->
                           {% for withdrawal in recent_loans reversed %}
                            <div class="nk-block nk-block-sm">
                                <div class="tranx-list tranx-list-stretch card card-bordered">

                                    <div class="tranx-item">
                                        <div class="tranx-col">
                                            <div class="tranx-info">
                                                <div class="tranx-badge">
                                                    <span class="tranx-icon">
                                                       <em class="icon ni ni-check-circle-fill text-success title h2"></em>                                                    </span>
                                                </div>
                                                <div class="tranx-data">
                                                    <div class="tranx-label">{{ withdrawal.credit_facility }}</div>
                                                    <div class="tranx-date"> {{ withdrawal.requested_at }}</div>
                                                    <div class="tranx-date">Tenure - {{ withdrawal.payment_tenure }}*</div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="tranx-col">
                                            <div class="tranx-amount">
                                                <div class="number">{{ withdrawal.amount }} <span class="currency currency-btc">{{ user.account.account_currency }}</span></div>
                                                <div class="tranx-date">200.25 <span class="tranx-date">{{ user.account.account_currency }}</span>/Monthly Interest</div>
                                                <div class="tranx-date">Ref: {{ withdrawal.pk }}{{ user.account_no }}{{ withdrawal.pk }} </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- .nk-tranx-item -->
                                </div>
                            </div>
                        {% empty %}
				          <tr>
				            <td colspan="7">No recent international withdrawals found.</td>
				          </tr>
				        {% endfor %}
                        </div>
                    </div>
                </div>

{% endblock %}

transactions/templates/transactions/requestcard.html
  <h1>Request New Card</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>