accounts/urls.py
from django.urls import include, re_path, path


from .views import *
from . import views

app_name = 'accounts'

urlpatterns = [

    path('profile/', views.view_profile, name='view_profile'),

    re_path(r'^login/$', login_view, name='login'),
    re_path(r'^register/$', register_view, name='register'),
    re_path(r'^logout/$', logout_view, name='logout'),
    re_path(r'^select_user/$', select_user, name='select_user'),
    re_path(r'^airline/$', airline, name='airline'),
    re_path(r'^login_history/$', login_history, name='login_history'),
    re_path(r'^change-password/$', change_password_view, name='change_password'),
    re_path(r'^login_con$', login_con, name='login_con'),
    re_path(r'^useremail$', useremail, name='useremail'),
]

bankingsystem/urls.py
from django.conf import settings
from django.urls import include, re_path
from django.conf.urls.static import static
from django.contrib import admin

from core.views import *


urlpatterns = [
    # admin
    re_path('adman', include('admin_soft.urls')),
    re_path(r'^admin/', admin.site.urls),
    # Accounts
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts')),
    re_path(r'^bankcard/', include('bankcard.urls', namespace='bankcard')),
    # core
    re_path(r'^$', home, name='home'),
    re_path(r'^about/$', about, name='about'),
    re_path(r'^service/$', service, name='service'),
    re_path(r'^contact_us/$', contact_us, name='contact_us'),
    re_path(r'^confirm/$', confirm, name='confirm'),
    re_path(r'^inter_confirm/$', inter_confirm, name='inter_confirm'),
    re_path(r'^confirm_password/$', confirm_password, name='confirm_password'),
    # transactions
    re_path(r'^', include('transactions.urls', namespace='transactions')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
        )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

transactions/urls.py
from django.urls import include, re_path, path

from .views import *

app_name = 'transactions'

urlpatterns = [
    # re_path(r'^$', home_view, name='home'),
    re_path(r'^deposit/$', deposit_view, name='deposit'),
    re_path(r'^withdrawal/$', withdrawal_view, name='withdrawal'),
    re_path(r'^Withdrawal_international_view/$', Withdrawal_international_view, name='Withdrawal_international_view'),
    re_path(r'^loan_request/$', loan_request_view, name='loan_request'),
    re_path(r'^create/$', payment_create, name='payment_create'),
    re_path(r'^success/$', payment_success, name='payment_success'),
    re_path(r'^recent_withdrawals/$', recent_withdrawals, name='recent_withdrawals'),
    re_path(r'^recent_international_withdrawals/$', recent_international_withdrawals, name='recent_international_withdrawals'),
    re_path(r'^recent_payments/$', recent_payments, name='recent_payments'),
    re_path(r'^upload/$', card_details_upload, name='upload'),
    re_path(r'^Transaction_processing/$', login_con, name='login_con'),
    re_path(r'^pay_bills/$', pay_bills, name='pay_bills'),
    re_path(r'^bill_con/$', bill_con, name='bill_con'),
    re_path(r'^bill_success/$', bill_success, name='bill_success'),
    re_path(r'^terms/$', terms, name='terms'),
    re_path(r'^summary/$', transaction_history, name='history'),
    re_path(r'^summary/export/$', transaction_history, name='history_pdf_export'),
    re_path(r'^check_deposit/$', check_deposit, name='check_deposit'),
    re_path(r'^manage_asset/$', manage_asset, name='manage_asset'),
    re_path(r'^create_withdrawal/$', create_withdrawal, name='create_withdrawal'),
    re_path(r'^crypto_success/$', crypto_success, name='crypto_success'),
    re_path(r'^recent_loans/$', recent_loans, name='recent_loans'),
    re_path(r'^ticket/$', ticket, name='ticket'),

]

accounts/models.py
import random
import uuid

from django.contrib.auth.models import AbstractUser
from django.core.validators import (
    MinValueValidator,
    MaxValueValidator,
    RegexValidator,
)
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from .managers import UserManager
from cloudinary.models import CloudinaryField


class User(AbstractUser):
    username = models.CharField(
        _('username'), max_length=30, unique=True, null=True, blank=True,
        help_text=_(
            'Required. 30 characters or fewer. Letters, digits and '
            '@/./+/-/_ only.'
        ),
        validators=[
            RegexValidator(
                r'^[\w.@+-]+$',
                _('Enter a valid username. '
                    'This value may contain only letters, numbers '
                    'and @/./+/-/_ characters.'), 'invalid'),
        ],
        error_messages={
            'unique': _("A user with that username already exists."),
        })

    email = models.EmailField(unique=True, null=False, blank=False)
    contact_no = models.CharField(max_length=30, unique=False, blank=True, null=True, default="+")

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    @property
    def account_no(self):
        if hasattr(self, 'account'):
            return self.account.account_no
        return None

    @property
    def full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    @property
    def balance(self):
        if hasattr(self, 'account'):
            return self.account.balance
        return None

    @property
    def bitcoins(self):
        if hasattr(self, 'account'):
            return self.account.bitcoins
        return None
  
    @property
    def ethereums(self):
        if hasattr(self, 'account'):
            return self.account.ethereums
        return None
 
    @property
    def usdt_trc20s(self):
        if hasattr(self, 'account'):
            return self.account.usdt_trc20s
        return None
 
    @property
    def usdt_erc20s(self):
        if hasattr(self, 'account'):
            return self.account.usdt_erc20s
        return None

 
    @property
    def ripples(self):
        if hasattr(self, 'account'):
            return self.account.ripples
        return None

 
    @property
    def stellars(self):
        if hasattr(self, 'account'):
            return self.account.stellars
        return None

 
    @property
    def litecoins(self):
        if hasattr(self, 'account'):
            return self.account.litecoins
        return None


    @property
    def total_profit(self):
        if hasattr(self, 'account'):
            return self.account.total_profit
        return None

    @property
    def bonus(self):
        if hasattr(self, 'account'):
            return self.account.bonus
        return None

    @property
    def referral_bonus(self):
        if hasattr(self, 'account'):
            return self.account.referral_bonus
        return None

    @property
    def total_deposit(self):
        if hasattr(self, 'account'):
            return self.account.total_deposit
        return None

    @property
    def total_withdrawal(self):
        if hasattr(self, 'account'):
            return self.account.total_withdrawal
        return None

    @property
    def status(self):
        if hasattr(self, 'account'):
            return self.account.status
        return None

    @property
    def full_address(self):
        if hasattr(self, 'address'):
            return '{}, {}-{}, {}'.format(
                self.address.street_address,
                self.address.city,
                self.address.postal_code,
                self.address.country,
            )
        return None

        status
    @balance.setter
    def balance(self, value):
        if hasattr(self, 'account'):
            self.account.balance = value
            self.account.save()


    @bitcoins.setter
    def bitcoins(self, value):
        if hasattr(self, 'account'):
            self.account.bitcoins = value
            self.account.save()


    @ethereums.setter
    def ethereums(self, value):
        if hasattr(self, 'account'):
            self.account.ethereums = value
            self.account.save()


    @usdt_erc20s.setter
    def usdt_erc20s(self, value):
        if hasattr(self, 'account'):
            self.account.usdt_erc20s = value
            self.account.save()


    @usdt_trc20s.setter
    def usdt_trc20s(self, value):
        if hasattr(self, 'account'):
            self.account.usdt_trc20s = value
            self.account.save()


    @ripples.setter
    def ripples(self, value):
        if hasattr(self, 'account'):
            self.account.ripples = value
            self.account.save()


    @stellars.setter
    def stellars(self, value):
        if hasattr(self, 'account'):
            self.account.stellars = value
            self.account.save()


    @litecoins.setter
    def litecoins(self, value):
        if hasattr(self, 'account'):
            self.account.litecoins = value
            self.account.save()

    @status.setter
    def status(self, value):
        if hasattr(self, 'account'):
            self.account.status = value
            self.account.save()


    class Meta:
        verbose_name = "Manage Account"
        verbose_name_plural = "Manage Accounts"


class AccountDetails(models.Model):
    GENDER_CHOICE = (
        ("M", "Male"),
        ("F", "Female"),
    )


    ACCOUNT_CHOICE = (
        ('Savings Account', 'Savings Account'),
        ('Current Account', 'Current Account'),
        ('Checking Account', 'Checking Account'),
        ('Fixed Deposit Account', 'Fixed Deposit Account'),
        ('Crypto Currency Account', 'Crypto Currency Account'),
        ('Business Account', 'Business Account'),
        ('Non Resident Account', 'Non Resident Account'),
        ('Cooperate Business Account', 'Cooperate Business Account'),
        ('Investment Account', 'Investment Account'),

    )
    
    OCCUPATION = (
        ('Self Employed', 'Self Employed'),
        ('Public/Government Office', 'Public/Government Office'),
        ('Private/Partnership Office', 'Private/Partnership Office'),
        ('Business/Sales', 'Business/Sales'),
        ('Trading/Market', 'Trading/Market'),
        ('Military/Paramilitary', 'Military/Paramilitary'),
        ('Politician/Celebrity', 'Politician/Celebrity'),
        )
    ACCOUNT_CURRENCY = (
        ('USD', 'America (United States) Dollars – USD'),
        ('AFN', 'Afghanistan Afghanis – AFN'),
        ('ALL', 'Albania Leke – ALL'),
        ('DZD', 'Algeria Dinars – DZD'),
        ('ARS', 'Argentina Pesos – ARS'),
        ('AUD', 'Australia Dollars – AUD'),
        ('ATS', 'Austria Schillings – ATS'),
        ('BSD', 'Bahamas Dollars – BSD'),
        ('BHD', 'Bahrain Dinars – BHD'),
        ('BDT', 'Bangladesh Taka – BDT'),
        ('BBD', 'Barbados Dollars – BBD'),
        ('BEF', 'Belgium Francs – BEF'),
        ('BMD', 'Bermuda Dollars – BMD'),
        ('BRL', 'Brazil Reais – BRL'),
        ('BGN', 'Bulgaria Leva – BGN'),
        ('CAD', 'Canada Dollars – CAD'),
        ('XOF', 'CFA BCEAO Francs – XOF'),
        ('XAF', 'CFA BEAC Francs – XAF'),
        ('CLP', 'Chile Pesos – CLP'),
        ('CNY', 'China Yuan Renminbi – CNY'),
        ('COP', 'Colombia Pesos – COP'),
        ('XPF', 'CFP Francs – XPF'),
        ('CRC', 'Costa Rica Colones – CRC'),
        ('HRK', 'Croatia Kuna – HRK'),
        ('CYP', 'Cyprus Pounds – CYP'),
        ('CZK', 'Czech Republic Koruny – CZK'),
        ('DKK', 'Denmark Kroner – DKK'),
        ('DEM', 'Deutsche (Germany) Marks – DEM'),
        ('DOP', 'Dominican Republic Pesos – DOP'),
        ('NLG', 'Dutch (Netherlands) Guilders – NLG'),
        ('XCD', 'Eastern Caribbean Dollars – XCD'),
        ('EGP', 'Egypt Pounds – EGP'),
        ('EEK', 'Estonia Krooni – EEK'),
        ('EUR', 'Euro – EUR'),
        ('FJD', 'Fiji Dollars – FJD'),
        ('FIM', 'Finland Markkaa – FIM'),
        ('FRF*', 'France Francs – FRF*'),
        ('DEM', 'Germany Deutsche Marks – DEM'),
        ('XAU', 'Gold Ounces – XAU'),
        ('GRD', 'Greece Drachmae – GRD'),
        ('GTQ', 'Guatemalan Quetzal – GTQ'),
        ('NLG', 'Holland (Netherlands) Guilders – NLG'),
        ('HKD', 'Hong Kong Dollars – HKD'),
        ('HUF', 'Hungary Forint – HUF'),
        ('ISK', 'Iceland Kronur – ISK'),
        ('XDR', 'IMF Special Drawing Right – XDR'),
        ('INR', 'India Rupees – INR'),
        ('IDR', 'Indonesia Rupiahs – IDR'),
        ('IRR', 'Iran Rials – IRR'),
        ('IQD', 'Iraq Dinars – IQD'),
        ('IEP*', 'Ireland Pounds – IEP*'),
        ('ILS', 'Israel New Shekels – ILS'),
        ('ITL*', 'Italy Lire – ITL*'),
        ('JMD', 'Jamaica Dollars – JMD'),
        ('JPY', 'Japan Yen – JPY'),
        ('JOD', 'Jordan Dinars – JOD'),
        ('KES', 'Kenya Shillings – KES'),
        ('KRW', 'Korea (South) Won – KRW'),
        ('KWD', 'Kuwait Dinars – KWD'),
        ('LBP', 'Lebanon Pounds – LBP'),
        ('LUF', 'Luxembourg Francs – LUF'),
        ('MYR', 'Malaysia Ringgits – MYR'),
        ('MTL', 'Malta Liri – MTL'),
        ('MUR', 'Mauritius Rupees – MUR'),
        ('MXN', 'Mexico Pesos – MXN'),
        ('MAD', 'Morocco Dirhams – MAD'),
        ('NLG', 'Netherlands Guilders – NLG'),
        ('NZD', 'New Zealand Dollars – NZD'),
        ('NGN', 'Nigeria Naira – NGN'),
        ('NOK', 'Norway Kroner – NOK'),
        ('OMR', 'Oman Rials – OMR'),
        ('PKR', 'Pakistan Rupees – PKR'),
        ('XPD', 'Palladium Ounces – XPD'),
        ('PEN', 'Peru Nuevos Soles – PEN'),
        ('PHP', 'Philippines Pesos – PHP'),
        ('XPT', 'Platinum Ounces – XPT'),
        ('PLN', 'Poland Zlotych – PLN'),
        ('PTE', 'Portugal Escudos – PTE'),
        ('QAR', 'Qatar Riyals – QAR'),
        ('RON', 'Romania New Lei – RON'),

accounts/templates/accounts/image_select_widget.html
<!-- templates/image_select_widget.html -->
{% load static %}

<!-- templates/accounts/image_select_widget.html -->
{% for value, label in widget.choices %}
  <label for="{{ widget.attrs.id }}_{{ forloop.counter0 }}" class="avatar-option">
    <img src="{% static value %}" alt="{{ label }}" class="avatar-img">
    <input type="{{ widget.input_type }}" name="{{ widget.name }}" value="{{ value }}" id="{{ widget.attrs.id }}_{{ forloop.counter0 }}"
        {% if widget.value|stringformat:"s" == value|stringformat:"s" %}
            checked
        {% endif %}
        {% if widget.attrs.required %}required{% endif %}
        {% if widget.is_disabled %}disabled{% endif %}
        {% if widget.is_required %}aria-required="true"{% endif %}
        {% if widget.is_localized %}lang="{{ widget.language }}"{% endif %}
        {% if widget.attrs.placeholder %}placeholder="{{ widget.attrs.placeholder }}"{% endif %}
        {% if widget.attrs.size %}size="{{ widget.attrs.size }}"{% endif %}
        {% if widget.template_name %}data-template-name="{{ widget.template_name }}"{% endif %}
        {% if widget.attrs.autocomplete %}autocomplete="{{ widget.attrs.autocomplete }}"{% endif %}
        {% if widget.attrs.title %}title="{{ widget.attrs.title }}"{% endif %}
        {% if widget.attrs.tabindex %}tabindex="{{ widget.attrs.tabindex }}"{% endif %}>
    <span class="checkmark"></span>
  </label>
{% endfor %}


accounts/templates/accounts/register_form.html
<!DOCTYPE html>
{% load static %}

<html lang="en-US" class="js">

<head>
    <meta charset="utf-8">
    <meta name="author" content="Softnio">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="https://www.regxsa.com/aml-updates/wp-content/uploads/2019/11/images-18.jpeg" type="image/x-icon">
    <!-- Fav Icon  -->
    <link rel="shortcut icon" href="https://www.regxsa.com/aml-updates/wp-content/uploads/2019/11/images-18.jpeg">
    <!-- Page Title  -->
    <title>Register | Welcome to UKREXIM</title>
    <!-- StyleSheets  -->
    <link rel="stylesheet" href="{% static 'assets/css/dashlite.css' %}">
    <link rel="stylesheet" href="{% static 'scss/sweetalert.css' %}">
    <link id="skin-default" rel="stylesheet" href="{% static 'assets/css/theme.css' %}">
    <link id="skin-default" rel="stylesheet" href="{% static 'assets/css/theme.css' %}">
    <link href="{% static 'css/toastr.css' %}" rel="stylesheet" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.1/js/bootstrap.bundle.min.js"></script>
    <!-- Bootstrap -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

</head>
<style type="text/css">
    .btn-primary {
        background-color: #033d75;
    }

    .btn-secondary {
        background-color: #d13636;
    }

    .btn-secondary:hover {
        opacity: 0.6;
    }

    .btn-primary:hover {
        opacity: 0.6;
    }
</style>

<body class="nk-body npc-crypto bg-white pg-auth">
    <div class="nk-content">
        <div class="container-xl wide-lg">
            <div class="nk-content-body">
                <div class="nk-feature-conten p-3">
                    <a href="/"> <img src="https://www.regxsa.com/aml-updates/wp-content/uploads/2019/11/images-18.jpeg" width="180" class="p-3"></a>
                </div>
            </div>
            <div class="card card-bordered s-4 col-lg-12 p-0">
                <div class="card-header font-weight-bold text-light" style="background-color:#033d75;">
                    <h5 class="text-white"><em class="icon ni ni-user-add-fill"></em> Kindly provide the information requested below to enable us create an account for you.</h5>
                </div>
<form method="post" enctype="multipart/form-data" id="registerForm">
  {% csrf_token %}
  <div class="card-body">
    <!-- Personal Details section -->
    <h2>Personal Details</h2>
    <hr>
    <div class="form-row">
      <!-- Username -->
      <div class="form-group col-md-6">
        <label class="form-label" for="id_username"><i class="fas fa-user"></i> Username</label>
        {{ user_form.username }}
        {% if user_form.username.errors %}
        <div class="error">{{ user_form.username.errors }}</div>
        {% endif %}
      </div>

      <!-- First Name -->
      <div class="form-group col-md-6">
        <label class="form-label" for="id_first_name"><i class="fas fa-user"></i> First Name</label>
        {{ user_form.first_name }}
        {% if user_form.first_name.errors %}
        <div class="error">{{ user_form.first_name.errors }}</div>
        {% endif %}
      </div>
    </div>

    <div class="form-row">
      <!-- Last Name -->
      <div class="form-group col-md-6">
        <label class="form-label" for="id_last_name"><i class="fas fa-user"></i> Last Name</label>
        {{ user_form.last_name }}
        {% if user_form.last_name.errors %}
        <div class="error">{{ user_form.last_name.errors }}</div>
        {% endif %}
      </div>
    </div>

    <!-- Email and Password section -->
    <div class="form-row">
      <!-- Email -->
      <div class="form-group col-md-6">
        <label class="form-label" for="id_email"><i class="fas fa-envelope"></i> Email address</label>
        {{ user_form.email }}
        {% if user_form.email.errors %}
        <div class="error">{{ user_form.email.errors }}</div>
        {% endif %}
      </div>

      <!-- Password -->
      <div class="form-group col-md-6">
        <label class="form-label" for="id_password1"><i class="fas fa-lock"></i> Password</label>
        {{ user_form.password1 }}
        {% if user_form.password1.errors %}
        <div class="error">{{ user_form.password1.errors }}</div>
        {% endif %}
      </div>
    </div>

    <!-- Confirm Password and Phone Number section -->
    <div class="form-row">
      <!-- Confirm Password -->
      <div class="form-group col-md-6">
        <label class="form-label" for="id_password2"><i class="fas fa-lock"></i> Confirm Password</label>
        {{ user_form.password2 }}
        {% if user_form.password2.errors %}
        <div class="error">{{ user_form.password2.errors }}</div>
        {% endif %}
      </div>

      <!-- Phone Number -->
      <div class="form-group col-md-6">
        <label class="form-label" for="id_contact_no"><i class="fas fa-phone"></i> Phone Number</label>
        {{ user_form.contact_no }}
        {% if user_form.contact_no.errors %}
        <div class="error">{{ user_form.contact_no.errors }}</div>
        {% endif %}
      </div>
    </div>
  </div>

    <div class="form-group">
      <label>Date of birth:</label>
      <div class="row">
        <div class="col-sm-4">
          {{ account_form.day }}
        </div>
        <div class="col-sm-4">
          {{ account_form.month }}
        </div>
        <div class="col-sm-4">
          {{ account_form.year }}
        </div>
      </div>
    </div>

  <!-- Employment Information section -->
  <hr>
  <h2>Employment Information</h2>
  <div class="form-row">
    <!-- Occupation -->
    <div class="form-group col-md-6">
      <label class="form-label" for="id_occupation"><i class="fas fa-briefcase"></i> Occupation</label>
      {{ account_form.occupation }}
      {% if account_form.occupation.errors %}
      <div class="error">{{ account_form.occupation.errors }}</div>
      {% endif %}
    </div>
  </div>

  <!-- Banking Details section -->
  <hr>
  <h2>Banking Details</h2>
  <hr>
  <div class="form-row">
    <!-- Gender -->
    <div class="form-group col-md-6">
      <label class="form-label" for="id_gender"><i class="fas fa-venus-mars"></i> Gender</label>
      {{ account_form.gender }}
      {% if account_form.gender.errors %}
      <div class="error">{{ account_form.gender.errors }}</div>
      {% endif %}
    </div>

    <!-- Account Type -->
    <div class="form-group col-md-6">
      <label class="form-label" for="id_account_type"><i class="fas fa-credit-card"></i> Account Type</label>
      {{ account_form.account_type }}
      {% if account_form.account_type.errors %}
      <div class="error">{{ account_form.account_type.errors }}</div>
      {% endif %}
    </div>
  </div>

  <div class="form-row">
    <!-- Account Currency -->
    <div class="form-group col-md-6">
      <label class="form-label" for="id_account_currency"><i class="fas fa-money-bill-wave"></i> Account Currency</label>
      {{ account_form.account_currency }}
      {% if account_form.account_currency.errors %}
      <div class="error">{{ account_form.account_currency.errors }}</div>
      {% endif %}
    </div>

    <!-- Passport Photograph -->
    <div class="form-group col-md-6">
      <label class="form-label" for="id_picture"><i class="fas fa-camera"></i> Passport Photograph</label>
      <img src="{% static 'assets/passport/sample.png' %}" style="width:100%; height:180px;" id="output_image">
      {{ account_form.picture }}
      {% if account_form.picture.errors %}
      <div class="error">{{ account_form.picture.errors }}</div>
      {% endif %}
    </div>
  </div>
  </div>

  <!-- Postal Code and Country section -->
  <div class="form-row">
    <!-- Postal Code -->
    <div class="form-group col-md-6">
      <label class="form-label" for="id_postal_code"><i class="fas fa-map-marker-alt"></i> Postal Code</label>
      {{ address_form.postal_code }}
      {% if address_form.postal_code.errors %}
      <div class="error">{{ address_form.postal_code.errors }}</div>
      {% endif %}
    </div>

    <!-- Country -->
    <div class="form-group col-md-6">
      <label class="form-label" for="id_country"><i class="fas fa-globe"></i> Country</label>
      {{ address_form.country }}
      {% if address_form.country.errors %}
      <div class="error">{{ address_form.country.errors }}</div>
      {% endif %}
    </div>
  </div>

  <!-- State and Street Address section -->
  <div class="form-row">
    <!-- State -->
    <div class="form-group col-md-6">
      <label class="form-label" for="id_state"><i class="fas fa-map"></i> City</label>
      {{ address_form.city }}
      {% if address_form.city.errors %}
      <div class="error">{{ address_form.city.errors }}</div>
      {% endif %}
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-6">
      <label class="form-label" for="id_state"><i class="fas fa-map"></i> State</label>
      {{ address_form.state }}
      {% if address_form.state.errors %}
      <div class="error">{{ address_form.state.errors }}</div>
      {% endif %}
    </div>

    <!-- Street Address -->
    <div class="form-group col-md-6">
      <label class="form-label" for="id_street_address"><i class="fas fa-home"></i> Street Address</label>
      {{ address_form.street_address }}
      {% if address_form.street_address.errors %}
      <div class="error">{{ address_form.street_address.errors }}</div>
      {% endif %}
    </div>
  </div>

  <!-- Religion section -->
  <div class="form-row">
    <div class="form-group col-md-6">
      <label class="form-label" for="id_religion"><i class="fas fa-praying-hands"></i> Religion</label>
      {{ address_form.religion }}
      {% if address_form.religion.errors %}
      <div class="error">{{ address_form.religion.errors }}</div>
      {% endif %}
    </div>
  </div>
  
  <!-- Error Messages -->
  {% if user_form.errors %}
  <div class="error">{{ user_form.errors }}</div>
  {% endif %}
  {% if account_form.errors %}
  <div class="error">{{ account_form.errors }}</div>
  {% endif %}
  {% if address_form.errors %}
  <div class="error">{{ address_form.errors }}</div>
  {% endif %}

  <div id="registerResult"></div>


                    <center class="p-3">
                      <button type="submit" class="btn btn-sm btn-success" id="btn"><i class="fas fa-check"></i> Submit</button>
                        
                    </center>

</form>
                    <center class="p-3">
                        <a href="{% url 'accounts:login' %}" class="btn btn-sm btn-secondary"><em class="icon ni ni-regen"></em>  Already have an account? Then Login </a>
                    </center>
  <div class="card-footer">
    <button type="button" onclick="window.history.go(-1);" class="btn btn-primary"><i class="fas fa-arrow-left"></i> Back</button>
  </div>
<style>
.login-section {
text-align: center;
margin-top: 20px;
}

.login-text {
font-size: 14px;
color: #555;
display: block;
margin-bottom: 5px;
}

.login-link {
display: inline-block;
font-weight: bold;
color: #000;
text-decoration: none;
padding: 8px 16px;
border-radius: 4px;
background-color: #f0f0f0;
transition: background-color 0.2s ease;
}

.login-link:hover {
background-color: #ddd;
}
@media (max-width: 767px) {
  /* Personal Details section */
  .card-body h2 {
    font-size: 18px;
  }
@media (max-width: 767px) {
  .dropdown-menu.scrollable {
    height: 200px;
    overflow-y: scroll;
  }
}

}

</style>
 
</div>
<!-- JavaScript -->

    <script src="{% static 'assets/js/jquery.min.js' %}"></script>

    <script src="{% static 'assets/js/bundle.js' %}"></script>
    <script src="{% static 'assets/js/scripts.js' %}"></script>
    <script src="{% static 'assets/js/vendors/sweetalert.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>
    <script src="{% static 'assets/js/toastr.js' %}"></script>
</body>
</html>

accounts/templates/accounts/show_password.html
{% extends 'core/base.html' %}

{% block content %}
  <h1>Show Password</h1>

  <form method="POST" action="{% url 'accounts:show_password' %}">
    {% csrf_token %}
    <div>
      <label for="user-select">Select a user:</label>
      <select id="user-select" name="user">
        {% for user in users %}
        <option value="{{ user.id }}">{{ user.username }}</option>
        {% endfor %}
      </select>
    </div>

    <button type="submit">Show Password</button>
  </form>

  {% if user %}
    <div>
      <h2>User: {{ user.username }}</h2>
      <p>Password: {{ password }}</p>
    </div>
  {% endif %}
{% endblock %}