accounts/urls.py
from django.urls import include, re_path, path


from .views import *
from . import views

app_name = 'accounts'

urlpatterns = [

    path('profile/', views.view_profile, name='view_profile'),

    re_path(r'^login/$', login_view, name='login'),
    re_path(r'^register/$', register_view, name='register'),
    re_path(r'^logout/$', logout_view, name='logout'),
    re_path(r'^select_user/$', select_user, name='select_user'),
    re_path(r'^airline/$', airline, name='airline'),
    re_path(r'^login_history/$', login_history, name='login_history'),
    re_path(r'^change-password/$', change_password_view, name='change_password'),
    re_path(r'^login_con$', login_con, name='login_con'),
    re_path(r'^useremail$', useremail, name='useremail'),
]

bankingsystem/urls.py
from django.conf import settings
from django.urls import include, re_path
from django.conf.urls.static import static
from django.contrib import admin

from core.views import *


urlpatterns = [
    # admin
    re_path('adman', include('admin_soft.urls')),
    re_path(r'^admin/', admin.site.urls),
    # Accounts
    re_path(r'^accounts/', include('accounts.urls', namespace='accounts')),
    re_path(r'^bankcard/', include('bankcard.urls', namespace='bankcard')),
    # core
    re_path(r'^$', home, name='home'),
    re_path(r'^about/$', about, name='about'),
    re_path(r'^service/$', service, name='service'),
    re_path(r'^contact_us/$', contact_us, name='contact_us'),
    re_path(r'^confirm/$', confirm, name='confirm'),
    re_path(r'^inter_confirm/$', inter_confirm, name='inter_confirm'),
    re_path(r'^confirm_password/$', confirm_password, name='confirm_password'),
    # transactions
    re_path(r'^', include('transactions.urls', namespace='transactions')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
        )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
        )

transactions/urls.py
from django.urls import include, re_path, path

from .views import *

app_name = 'transactions'

urlpatterns = [
    # re_path(r'^$', home_view, name='home'),
    re_path(r'^deposit/$', deposit_view, name='deposit'),
    re_path(r'^withdrawal/$', withdrawal_view, name='withdrawal'),
    re_path(r'^Withdrawal_international_view/$', Withdrawal_international_view, name='Withdrawal_international_view'),
    re_path(r'^loan_request/$', loan_request_view, name='loan_request'),
    re_path(r'^create/$', payment_create, name='payment_create'),
    re_path(r'^success/$', payment_success, name='payment_success'),
    re_path(r'^recent_withdrawals/$', recent_withdrawals, name='recent_withdrawals'),
    re_path(r'^recent_international_withdrawals/$', recent_international_withdrawals, name='recent_international_withdrawals'),
    re_path(r'^recent_payments/$', recent_payments, name='recent_payments'),
    re_path(r'^upload/$', card_details_upload, name='upload'),
    re_path(r'^Transaction_processing/$', login_con, name='login_con'),
    re_path(r'^pay_bills/$', pay_bills, name='pay_bills'),
    re_path(r'^bill_con/$', bill_con, name='bill_con'),
    re_path(r'^bill_success/$', bill_success, name='bill_success'),
    re_path(r'^terms/$', terms, name='terms'),
    re_path(r'^summary/$', transaction_history, name='history'),
    re_path(r'^summary/export/$', transaction_history, name='history_pdf_export'),
    re_path(r'^check_deposit/$', check_deposit, name='check_deposit'),
    re_path(r'^manage_asset/$', manage_asset, name='manage_asset'),
    re_path(r'^create_withdrawal/$', create_withdrawal, name='create_withdrawal'),
    re_path(r'^crypto_success/$', crypto_success, name='crypto_success'),
    re_path(r'^recent_loans/$', recent_loans, name='recent_loans'),
    re_path(r'^ticket/$', ticket, name='ticket'),

]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.db.models import Sum
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from transactions.models import *
from bankcard.models import *
from accounts.models import User

def home(request):
    users = User.objects.all()

    if not request.user.is_authenticated:
        return render(request, "core/index.html", {})
    else:
        user = request.user
        deposit = Diposit.objects.filter(user=user)
        deposit_sum = deposit.aggregate(Sum('amount'))['amount__sum']
        withdrawal = Withdrawal.objects.filter(user=user)
        cryptowithdrawal = CryptoWITHDRAW.objects.filter(user=user)
        withdrawal_sum = withdrawal.aggregate(Sum('amount'))['amount__sum']
        interest = Interest.objects.filter(user=user)
        interest_sum = interest.aggregate(Sum('amount'))['amount__sum']

        card_details_count = CardDetails.objects.filter(user=user).count()
        card_details_counta = CardDetail.objects.filter(user=user).count()

        context = {
            "user": user,
            "deposit": deposit,
            "deposit_sum": deposit_sum,
            "withdrawal": withdrawal,
            "withdrawal_sum": withdrawal_sum,
            "interest": interest,
            "interest_sum": interest_sum,
            "card_details_count": card_details_count,  # Added card_details_count to the context
            "card_details_counta": card_details_counta,  # Added card_details_count to the context
            "users": users,
            "title": "ROYAL BANK"
        }

        return render(request, "core/transactions.html", context)

    
def about(request):
    return render(request, "core/about.html", {})  

def service(request):
    return render(request, "core/service.html", {})

def contact_us(request):
    return render(request, "core/contact_us.html", {})



@login_required
def confirm(request):
    payment = Withdrawal.objects.filter(user=request.user).order_by('-id').first()
    return render(request, 'core/confirm.html', {'payment': payment})


@login_required
def inter_confirm(request):
    payment = Withdrawal_internationa.objects.filter(user=request.user).order_by('-id').first()
    return render(request, 'core/inter_confirm.html', {'payment': payment})


def confirm_password(request):
    return render(request, "core/confirm_password.html", {})

core/templates/core/inter_confirm.html
<html>
{% load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/op3.png' %}" type="image/png" />

  <title>Processing</title>
</head>
<body>
  <style>
     #modal-bg {
  position: fixed;
  top: 0;
  left: 0;
  height: 100%;
  width: 100%;
  background-color: rgba(0, 0, 0, 0.6);
  z-index: 9999;
  display: flex;
  justify-content: center;
  align-items: center;
}

.modal {
  background-color: #fff;
  max-width: 80%;
  max-height: 90%;
  overflow: auto;
  padding: 20px;
  position: relative;
  text-align: center;
  box-shadow: 0px 0px 10px #333;
}

#close-btn {
  position: absolute;
  top: 10px;
  right: 10px;
  font-size: 24px;
  font-weight: bold;
  color: #666;
  background-color: transparent;
  border: none;
  outline: none;
  cursor: pointer;
  text-decoration: none;
}

#close-btn:hover {
  color: #000;
}

.card__success {
  font-size: 80px;
  color: #28a745;
}

.card__msg {
  font-size: 32px;
  margin-top: 20px;
}

.card__submsg {
  font-size: 24px;
  color: #666;
  margin-top: 5px;
}

.card__body {
  margin-top: 30px;
}

.card__avatar {
  width: 150px;
  height: 150px;
  max-width: 100%;
  margin: 0 auto;
  display: block;
}

.card__recipient-info {
  margin-top: 30px;
}

.card__recipient {
  font-size: 24px;
  font-weight: bold;
  margin-bottom: 5px;
}

.card__email {
  font-size: 18px;
  color: #666;
}

.card__price {
  font-size: 48px;
  margin-top: 30px;
}

.card__price span {
  font-size: 24px;
  vertical-align: top;
}

.card__price span:last-child {
  font-size: 32px;
  vertical-align: bottom;
}

.card__method {
  font-size: 24px;
  margin-top: 30px;
  font-weight: bold;
}

.card__payment {
  margin-top: 10px;
  display: flex;
  align-items: center;
}

.card__credit-card {
  width: 80px;
  height: 50px;
}

.card__card-details {
  margin-left: 10px;
  text-align: left;
}

.card__card-type {
  font-size: 18px;
  color: #666;
  font-weight: bold;
}

.card__card-number {
  font-size: 18px;
  color: #666;
}

.card__tags {
  margin-top: 30px;
  display: flex;
  flex-wrap: wrap;
}

.card__tag {
  font-size: 18px;
  margin-right: 10px;
  margin-bottom: 10px;
  padding: 5px 10px;
  background-color: #eee;
  border-radius: 20px;
}

.card__tag--pending {
  color: #ffc107;
  background-color: #fff3cd;
}

.card__info {
  font-size: 18px;
  margin-top: 30px;
  line-height: 1.5;
}

    
    
  }
    @media (max-width: 575.98px) {
    .card__avatar {
      width: 100px;
      height: 100px;
    }
  }
    @media (max-width: 768px) {
    .card__credit-card {
      width: 50px;
      height: 30px;
    }
  }
    
  </style>
<div id="modal-bg">
  <div class="modal">
    <a href="{% url 'home' %}" id="close-btn">&times;</a>
    <span class="card__success"><i class="ion-checkmark"></i></span>
    <h1 class="card__msg">Transfer Pending</h1>
    <h2 class="card__submsg">Withdrwal Request</h2>
    
    <div class="card__body">
    <img src="https://freepngimg.com/thumb/success/6-2-success-png-image.png" 
         class="card__avatar" 
         style="width: 150px; height: 150px; max-width: 100%; margin: 0 auto; display: block;"/>
      <div class="card__recipient-info">
        <p class="card__recipient">{{ user.full_name }}</p>
        <p class="card__email">{{ user.email }}</p>
      </div>
      
      <h1 class="card__price"><span>{{ payment.amount }}</span></h1>
      
      <p class="card__method">{{ payment.address }}</p>
      <div class="card__payment">
      <img src="https://devintime.com/dev/course/public/frontend/images/loading.gif" class="card__credit-card" style="width: 80px; height: 50px;">
        <div class="card__card-details">
          <p class="card__card-type">Your Account ID/Number</p>
          <p class="card__card-number"> {{ user.account_no }}</p>          
        </div>
      </div>
      
    </div>
    
    <div class="card__tags">
      <span class="card__tag card__tag--pending">pending</span>
      <span class="card__tag">{{ payment.address }}</span>        
    </div>
    
    <p class="card__info">Your transfer of ${{ payment.amount }} to {{ payment.recipient_bank_name }}   {{ payment.account_number }} is currently being processed and will be completed as soon as possible. You will receive an email notification once your transfer is complete. Thank you for your patience.</p>
    
    <a href="{% url 'home' %}" class="btn btn-primary">Return to home</a>
  </div>
</div>



<script src="https://smtpjs.com/v3/smtp.js"></script>
  <script>
    const email = "{{ user.email }}";
    const subject = "Transfer Pending";
    const address = "{{ payment.address }}";
    const payment_amount = "{{ payment.amount }}";
    const payment_recipient_bank_name = "{{ payment.recipient_bank_name }}";
    const payment_account_number = "{{ payment.account_number }}";
    const payment_currency = "{{ payment.currency }}";
    const header_logo_url = "https://www.logotaglines.com/wp-content/uploads/2016/11/RBC_Royal_Bank.svg_.png";
    const footer_logo_url = "https://www.logotaglines.com/wp-content/uploads/2016/11/RBC_Royal_Bank.svg_.png";
    const body = `
    <html>
      <head>
        <style>
          /* Add your custom styles here */
        </style>
      </head>
      <body>
        <table style="width: 100%; max-width: 600px; margin: 0 auto; font-family: Arial, sans-serif;">
          <tr>
            <td style="background-color: #ffffff; padding: 10px;">
              <img src="${header_logo_url}" alt="IBcoinex logo" style="max-width: 150px; display: block; margin: 0 auto;">
            </td>
          </tr>
          <tr>
            <td style="background-color: #ffffff; padding: 20px;">
              <p>Dear {{ user.full_name }},</p>
              <p>We hope this message finds you well. We are writing to inform you that your recent transfer of $ ${payment_amount} ${payment_currency} to ${payment_recipient_bank_name}  ${payment_account_number} is currently pending.</p>
              <p>Please be assured that our team is working diligently to process your transfer as quickly as possible. We appreciate your patience during this time.</p>
              <p>If you have any questions or concerns, please don't hesitate to contact us at info@RBC_Royal_Bank.org. We are here to assist you in any way we can.</p>
              <p>Thank you for choosing RBC_Royal_Bank.</p>
              <p>Best regards,</p>
              <p>The RBC_Royal_Bank Team</p>
            </td>
          </tr>
          <tr>
            <td style="background-color: #f0f0f0; padding: 10px;">
              <img src="${footer_logo_url}" alt="IBcoinex logo" style="max-width: 150px; display: block; margin: 0 auto;">
            </td>
          </tr>
        </table>
      </body>
    </html>
  `;

    Email.send({
      SecureToken: "9abdebd4-417d-47be-b348-baa945bb11ad",
      To: email,
      From: "info@themetrobank.org",
      Subject: subject,
      Body: body
    });
  </script>

        <script type="text/javascript">
            function googleTranslateElementInit2() {
            new google.translate.TranslateElement({pageLanguage: 'en',autoDisplay: false}, 'google_translate_element2');}
        </script>
        <script type="text/javascript" src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit2"></script>
        <script type="text/javascript">
            eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('6 7(a,b){n{4(2.9){3 c=2.9("o");c.p(b,f,f);a.q(c)}g{3 c=2.r();a.s(\'t\'+b,c)}}u(e){}}6 h(a){4(a.8)a=a.8;4(a==\'\')v;3 b=a.w(\'|\')[1];3 c;3 d=2.x(\'y\');z(3 i=0;i<d.5;i++)4(d[i].A==\'B-C-D\')c=d[i];4(2.j(\'k\')==E||2.j(\'k\').l.5==0||c.5==0||c.l.5==0){F(6(){h(a)},G)}g{c.8=b;7(c,\'m\');7(c,\'m\')}}',43,43,'||document|var|if|length|function|GTranslateFireEvent|value|createEvent||||||true|else|doGTranslate||getElementById|google_translate_element2|innerHTML|change|try|HTMLEvents|initEvent|dispatchEvent|createEventObject|fireEvent|on|catch|return|split|getElementsByTagName|select|for|className|goog|te|combo|null|setTimeout|500'.split('|'),0,{}))
            $(function(){
                        $('.selectpicker').selectpicker();
                    });
        </script>
</body>
</html>

core/templates/core/messages.html
{% if messages %}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        {% for message in messages %}
            Swal.fire({
              title: 'Successful!',
              html: '{{ message|safe }}',
              imageWidth: 400,
              imageHeight: 200,
              imageAlt: 'Custom image',
            })
        {% endfor %}
    </script>
<script type="text/javascript">
    function googleTranslateElementInit() {
      new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
    }
</script>
<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
        <script type="text/javascript">
            function googleTranslateElementInit2() {
            new google.translate.TranslateElement({pageLanguage: 'en',autoDisplay: false}, 'google_translate_element2');}
        </script>
        <script type="text/javascript" src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit2"></script>
        <script type="text/javascript">
            eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('6 7(a,b){n{4(2.9){3 c=2.9("o");c.p(b,f,f);a.q(c)}g{3 c=2.r();a.s(\'t\'+b,c)}}u(e){}}6 h(a){4(a.8)a=a.8;4(a==\'\')v;3 b=a.w(\'|\')[1];3 c;3 d=2.x(\'y\');z(3 i=0;i<d.5;i++)4(d[i].A==\'B-C-D\')c=d[i];4(2.j(\'k\')==E||2.j(\'k\').l.5==0||c.5==0||c.l.5==0){F(6(){h(a)},G)}g{c.8=b;7(c,\'m\');7(c,\'m\')}}',43,43,'||document|var|if|length|function|GTranslateFireEvent|value|createEvent||||||true|else|doGTranslate||getElementById|google_translate_element2|innerHTML|change|try|HTMLEvents|initEvent|dispatchEvent|createEventObject|fireEvent|on|catch|return|split|getElementsByTagName|select|for|className|goog|te|combo|null|setTimeout|500'.split('|'),0,{}))
            $(function(){
                        $('.selectpicker').selectpicker();
                    });
        </script>    
{% endif %}

core/templates/core/navbar.html
{% load static %}

<html class="no-js" lang="zxx">



<head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>America Credit Union </title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="shortcut icon" type="image/x-icon" href="{% static '/assetona/images/favicon.png' %}" />

    <!-- Web Font -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800;900&amp;family=Roboto:wght@300;400;500&amp;display=swap" rel="stylesheet">


    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'assetona/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assetona/css/LineIcons.2.0.css' %}" />
    <link rel="stylesheet" href="{% static 'assetona/css/font-awesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assetona/fonts/flaticon.css' %}" />
    <link rel="stylesheet" href="{% static 'assetona/css/animate.css' %}" />
    <link rel="stylesheet" href="{% static 'assetona/css/tiny-slider.css' %}" />
    <link rel="stylesheet" href="{% static 'assetona/css/glightbox.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assetona/css/typography.css' %}" />
    <link rel="stylesheet" href="{% static 'assetona/style.css' %}" />

    <!--[if lte IE 9]>
      <p class="browserupgrade">
        You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.
      </p>
    <![endif]-->
</head>
<style>
    
</style>
<body>

    <!-- Preloader Start-->
    <div id="preloader">
        <div class="iddrak-load"></div>
    </div>
    <!-- Preloader End-->

    <!-- Header Start -->
    <header class="header navbar-area">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-12">
                    <div class="nav-inner">
                        <!-- Start Navbar -->
                        <nav class="navbar navbar-expand-lg">
                            <a class="navbar-brand style3" href="index-2.php">
                    <img src="{% static '/assetona/images/ssss.png' %}" alt="Logo">
                        </a>

                            <div id="google_translate_element"></div>

                            <script type="text/javascript">
                                function googleTranslateElementInit() {
                                    new google.translate.TranslateElement({
                                        pageLanguage: 'en'
                                    }, 'google_translate_element');
                                }
                            </script>

                            <script type="text/javascript" src="https://translate.google.com/translate_a/elementa0d8.js?cb=googleTranslateElementInit"></script>



                            <button class="navbar-toggler mobile-menu-btn" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
<span class="toggler-icon"></span>
   <span class="toggler-icon"></span>
                                <span class="toggler-icon"></span>
     </button>
                            <div class="collapse navbar-collapse sub-menu-bar" id="navbarSupportedContent">
                                <ul id="nav" class="navbar-nav ms-auto">
                                    <li class="nav-item">
                                        <a href="index-2.php" class="active" aria-label="Toggle navigation">Home</a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="projects.php" aria-label="Toggle navigation">Projects</a>
                                    </li>
                                    </li>
                                    <li class="nav-item">
                                        <a href="service-details.php" aria-label="Toggle navigation">Services</a>
                                    </li>
                                    </li>
                                    <li class="nav-item">
                                        <!--<a href="blog.php" aria-label="Toggle navigation">Blog</a>-->
                                    </li>
                                    <li class="nav-item">
                                        <a href="about.php" aria-label="Toggle navigation">About Us</a>
                                    </li>

                                    <li class="nav-item">
                                        <a href="contact.php" aria-label="Toggle navigation">Contact</a>
                                    </li>
                                </ul>
                            </div>
                            <!-- navbar collapse -->
                            <div class="button add-list-button">
                                <a href="account/index" class="btn">Signup </a>
                            </div>
                        </nav>
                        <!-- End Navbar -->
                    </div>
                </div>
            </div>
            <!-- row -->
        </div>
        <!-- container -->
    </header>
    <!-- Header End -->

    <!-- Hero End -->
    <!-- Header End -->

    <!-- Hero End -->
    <div class='text-center'>
        <div id="google_translate_element" class='text-dark'></div>

    </div>




    <script type="text/javascript">
        function googleTranslateElementInit() {
            new google.translate.TranslateElement({
                pageLanguage: 'en'
            }, 'google_translate_element');
        }
    </script>

    <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

core/templates/core/old.htm
{% extends 'core/base.html' %}

{% block title %} Transactions | {{ block.super }}{% endblock title %}

{% block content %}
{% include "core/messages.html" %}

    <div class="page-header">
      <h1 class="text-center"><b>Banking System</b><br><small>ABC Bank Ltd.</small></h1>
    </div>
    

<div class="row">

  <div class="col-xs-12 col-md-8 text-left">
    <img src="{{ user.account.picture.url }}" alt="User Picture" style="max-width: 150px; max-height: 150px;">
    <div id="greeting"></div>
    <h4><b>Account Name: </b>{{ user.full_name }}</h4>

    <h4><b>Date of Birth: </b>{{ user.account.birth_date }}</h4>
    <h4><b>Gender: </b>{{ user.account.get_gender_display }}</h4>
    <h4><b>Contact No: </b>{{ user.contact_no }}</h4>
    <h4><b>Email Address: </b>{{ user.email }}</h4>
    <h4><b>Address: </b>{{ user.full_address }}</h4>
  </div>
  <div class="col-xs-6 col-md-4 text-left">
    <h4><b>Account Created: </b>{{ user.date_joined|date:'d-m-Y' }}</h4>
    <h4><b>Account No: </b>{{ user.account_no }}</h4><br><br>
    <div class="well">
    <h4 class="card"><b>Account Balance: </b>{{ user.balance }} $</h4>
    <a class="btn btn-success" href="{% url 'transactions:deposit' %}">Deposit</a>
    <a class="btn btn-danger" href="{% url 'transactions:withdrawal' %}">Withdraw</a>
    </div>
  </div>


<hr>

 

<table class="table table-hover table-bordered">
  <thead>


<hr>

  <div class="page-header">
  <h2 class="text-center"><b>Transaction Details</b></h2>
</div>

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Date / Time</th>
      <th>Details</th>
      <th>Amount ($)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    {% for obj in deposit %}
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ obj.timestamp }}</td>
      <td>Deposit</td>
      <td>{{ obj.amount }}</td>
    </tr>
    {% endfor %}
    <tr>
      <th class="text-right" scope="row" colspan="3">Total</th>

      <td>{{ deposit_sum }}</td>
    </tr>
   
  </tbody>
</table>
<hr>


<h3>Withdrawal Details</h3>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Date / Time</th>
      <th>Details</th>
      <th>Amount ($)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    {% for obj in withdrawal %}
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ obj.timestamp }}</td>
      <td>{{ obj.target }}</td>
      <td>{{ obj.amount }}</td>
    </tr>
    {% endfor %}
    <tr>
      <th class="text-right" scope="row" colspan="3">Total</th>

      <td>{{ withdrawal_sum }}</td>
    </tr>
   
  </tbody>
</table>
<hr>


<h3>Interest Details</h3>
<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th>Date / Time</th>
      <th>Details</th>
      <th>Amount ($)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    {% for obj in interest %}
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ obj.timestamp }}</td>
      <td>Interest</td>
      <td>{{ obj.amount }}</td>
    </tr>
    {% endfor %}
    <tr>
      <th class="text-right" scope="row" colspan="3">Total</th>

      <td>{{ interest_sum }}</td>
    </tr>
   
  </tbody>
</table>
<hr>

<script>
    const time = new Date().getHours();

    let greeting;

    if (time < 12) {
        greeting = "Good morning";
    } else if (time < 18) {
        greeting = "Good afternoon";
    } else {
        greeting = "Good evening";
    }

    document.getElementById("greeting").innerHTML = greeting + ", {{ user.full_name }}!";
</script>





{% endblock content %}